[[Foldseek]]
arch = "aarch64"
git-tree-sha1 = "6285ccf11f169581b65223804387aa8e7f089709"
os = "macos"

    [[Foldseek.download]]
    sha256 = "ef4acae92ff284d6df7ffccf9a4ce2f0ae88831817b8f60f3c0d9ef35c140cf0"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.aarch64-apple-darwin.tar.gz"
[[Foldseek]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3ead1e1fb861b0f9c52c9e3770a2ffb2f80bb4d"
libc = "glibc"
os = "linux"

    [[Foldseek.download]]
    sha256 = "ea44241bf7a916ad1f1789b73b9a2d9e3ab5459bb7d30ec3412d0dd81775aa62"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Foldseek]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed50d57e7e5e14e1087387ea716f905eaf9401f9"
libc = "glibc"
os = "linux"

    [[Foldseek.download]]
    sha256 = "c19a9c26993c3bef3693fa138c199cdc346440f36315826e4dc586d291b8e319"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Foldseek]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dc8b452528acf1517106a9c494dc3e965ddf0ce"
libc = "musl"
os = "linux"

    [[Foldseek.download]]
    sha256 = "0842b90f4fd196c556bc98f9b40526384c7ef3c1cf0065543218d7a6826d0752"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Foldseek]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55a445d906c41ed22fcded2fac7c475ac9d82b2e"
libc = "musl"
os = "linux"

    [[Foldseek.download]]
    sha256 = "afc5117f4f9223b92992a985573e288f5c0dcfc34a9a7aa4f0d94b255525bf55"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Foldseek]]
arch = "x86_64"
git-tree-sha1 = "a57af6c0d14b348938c760094a6a410c11c09790"
os = "macos"

    [[Foldseek.download]]
    sha256 = "3ef7864606ef09800f71ae65099ea7932baf903d3ab1f5f16247c2025f884113"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.x86_64-apple-darwin.tar.gz"
[[Foldseek]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6228fc490ca964f8e65bcb60ff2456a875fc4852"
libc = "glibc"
os = "linux"

    [[Foldseek.download]]
    sha256 = "243064a9a5fea160684f0ea01025914a622a571109083c2ef904bac28458168b"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Foldseek]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dce30d62cb992bc0d07b3f545af993f1b18d6767"
libc = "glibc"
os = "linux"

    [[Foldseek.download]]
    sha256 = "fb601f93a4d0b9f44abac2d614be029e7773b804539af2676e413695f362289b"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Foldseek]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1f62be8439949659ee1c5b5c329a3b2f85aeb24"
libc = "musl"
os = "linux"

    [[Foldseek.download]]
    sha256 = "e426ab3e4b73a5913681b236bd2ea79209190897002e10813cad4f08ca2aa13b"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Foldseek]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e15a8fc4c30d461b4760fde2ea47d409b9140d73"
libc = "musl"
os = "linux"

    [[Foldseek.download]]
    sha256 = "e4c5ddada07385b1254d69e114a5baaba786a6b423483871327492f77debbf6e"
    url = "https://github.com/JuliaBinaryWrappers/Foldseek_jll.jl/releases/download/Foldseek-v6.0.0+0/Foldseek.v6.0.0.x86_64-linux-musl-cxx11.tar.gz"
