# Autogenerated wrapper script for Foldseek_jll for x86_64-apple-darwin
export foldseek

using Zlib_jll
using Bzip2_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("Foldseek")
JLLWrappers.@declare_executable_product(foldseek)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Bzip2_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_executable_product(
        foldseek,
        "bin/foldseek",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
